services:
  - type: web
    name: n8n
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: n8n
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWOR
        value: behbeh123
      - key: N8N_HOST
        fromService:
          type: web
          name: n8n
          property: host
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: "5678"
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: postgres
          name: n8n-postgres
          property: host
      - key: DB_POSTGRESDB_PORT
        fromService:
          type: postgres
          name: n8n-postgres
          property: port
      - key: DB_POSTGRESDB_USER
        fromService:
          type: postgres
          name: n8n-postgres
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: postgres
          name: n8n-postgres
          property: password
  - type: postgres
    name: n8n-postgres
    plan: free
    databaseName: n8n
